### ISSUE TITLE
tab Five characters(tab 只能五個字元？？）

### ISSUE THREAD

**Issue by Adenlin** [q805699513/PagerSlidingTabStrip#1]
請問 tab 有辦法讓他的字數更多嗎？因為目前好像超過第五個字元都會被卡掉
![1499681467769](https://user-images.githubusercontent.com/24599428/28013452-b2c1bea6-659b-11e7-969a-50837c27769d.jpg)

Will the tab have a way to make his words more? Because the current seems to be more than the fifth character will be transferred

**Comment by q805699513** [comment]
可以的，要修改布局xml源码，加大tab他的宽度，不过一般有大量tab的时候显示5个字已经够多了

**Comment by q805699513** [comment]
我在res/layout/布局里面设置了android:maxLength="5"这个参数，你需要修改下。我忘记考虑英文的情况下了。你可以把这个参数去掉

**Comment by raghul1992** [comment]
I am wondering the same, any way to make the title have its full length ?

**Comment by q805699513** [comment]
@raghul1992 new version compile 'com.longsh:PagerSlidingTabStrip:1.0.1'
