### ISSUE TITLE
效果显示

### ISSUE THREAD

**Issue by kevinStrange** [q805699513/PagerSlidingTabStrip#2]
想要实现第一张图片tablayout下面的选项跟着item大小变化需要引用哪个包呢

**Comment by q805699513** [comment]
都可以的。1.0就行了

**Comment by kevinStrange** [comment]
![741086109780378423](https://user-images.githubusercontent.com/6127122/45144351-7354ba00-b1f0-11e8-8616-85819eec8a0b.png)
效果如图

**Comment by q805699513** [comment]
@kevinStrange           //设置指示器Indicatorin是否跟文本一样宽，默认false
          tabs.setIndicatorinFollowerTv(true);

**Comment by kevinStrange** [comment]
![659067245001522510](https://user-images.githubusercontent.com/6127122/45144401-94b5a600-b1f0-11e8-9b71-acb3114eadb7.png)
没办法使用，很难滑动，而且位置对不上

**Comment by q805699513** [comment]
没出现过你这种问题，可以参考demo使用

**Comment by q805699513** [comment]
@kevinStrange 可能是参数设置问题，或者框架内部问题。可以先看看参数设置调整后还有没有问题

**Comment by kevinStrange** [comment]
![25f4e88337807527eaf6df63716b511](https://user-images.githubusercontent.com/6127122/45144958-18bc5d80-b1f2-11e8-9314-518b47d08bc1.png)
老铁，我想实现左边那种选中效果，但是你的demo是右边的效果，这个怎么修改呢

**Comment by q805699513** [comment]
@kevinStrange tabs.setIndicatorinFollowerTv(true);

**Comment by kevinStrange** [comment]
其他不需要修改吗，我代码是按照你的demo来的，你可以下载你的demo看一下，就算设置了tabs.setIndicatorinFollowerTv(true);也没有那个效果

**Comment by kevinStrange** [comment]
可以了，原来是代码在后面又将该值设置为false了
