### ISSUE TITLE
能否自定义tab选择第几个

### ISSUE THREAD

**Issue by FlyBiao** [q805699513/PagerSlidingTabStrip#5]
请问 这个控件能否自定义设置当前选中的是第几个tab呢？现在默认都是选中第一个的

**Comment by q805699513** [comment]
可以，这个是viewpager的功能，跟库没关系，设置viewpager显示到那页就行了。

**Comment by FlyBiao** [comment]
可以了   谢谢！

**Comment by zhudaihao** [comment]
设置选择需要的fragment，但是对应被选中的文本颜色没有改变？

**Comment by zhudaihao** [comment]
![7 d2 qh22lzp2d vfu re](https://user-images.githubusercontent.com/23647854/53711034-30139500-3e7b-11e9-903c-7ce731e4826c.jpg)

**Comment by zhudaihao** [comment]
![Uploading IMG_1673.JPG…]()

**Comment by zhudaihao** [comment]
![xsk7m ec38pv215xx h i](https://user-images.githubusercontent.com/23647854/53711218-0eff7400-3e7c-11e9-82ce-3c206251a659.png)

**Comment by q805699513** [comment]
稍等，等下看看问题

**Comment by q805699513** [comment]
@zhudaihao @q805699513

**Comment by zhudaihao** [comment]
setCurrentItem放最后就好了，谢谢
