### ISSUE TITLE
红点未显示

### ISSUE THREAD

**Issue by GuoLiangjun123** [q805699513/PagerSlidingTabStrip#6]
//设置小红点提示，item从0开始计算，true为显示，false为隐藏，默认为全部隐藏
        pagerSlidingTabStrip.setMsgToast(0, true);
        //设置红点滑动到当前页面自动消失,默认为true
        pagerSlidingTabStrip.setMsgToastPager(false);

**Comment by hopper9527** [comment]
请问该项目还在维护吗

**Comment by q805699513** [comment]
第0个item没显示红点？@GuoLiangjun123

**Comment by hopper9527** [comment]
> 第0个item没显示红点？@GuoLiangjun123
 无论设置哪个都不行

**Comment by q805699513** [comment]
把设置的代码放到后面。@GuoLiangjun123

**Comment by q805699513** [comment]
设置红点的代码放在最后面就可以了

**Comment by q805699513** [comment]
@GuoLiangjun123应该可以了吧，如果后面调用了tabs.notifyDataSetChanged()，需要在这个后面重新设置一下红点显示

**Comment by hopper9527** [comment]
> @GuoLiangjun123应该可以了吧，如果后面调用了tabs.notifyDataSetChanged()，需要在这个后面重新设置一下红点显示

谢谢小哥 666 这个项目很棒！

**Comment by hopper9527** [comment]
> @GuoLiangjun123应该可以了吧，如果后面调用了tabs.notifyDataSetChanged()，需要在这个后面重新设置一下红点显示

有红点的item下面的指示器不是在item的正下方   有点偏移

**Comment by hopper9527** [comment]
> @GuoLiangjun123应该可以了吧，如果后面调用了tabs.notifyDataSetChanged()，需要在这个后面重新设置一下红点显示

小哥您好，好像没有地方设置红点的大小样式。。。我想把红点设置得稍微大一点

**Comment by q805699513** [comment]
@GuoLiangjun123目前没这个设置，可以自行修改源码xml实现
